### ISSUE TITLE
Continually write to one sector causes error "Journal is full"

### ISSUE THREAD

**Issue by rgwan** [dlbeer/dhara#1]
Continually write to a sector causes error "Journal is full". I called GC, but it doesn't help.

**Comment by dlbeer** [comment]
On Sat, May 14, 2016 at 10:43:41PM -0700, ZhiYuan Wan wrote:
> Continually write to a sector causes error "Journal is full". I called GC, but it doesn't help.

Do you have a test program that reproduces the problem? I just tried
here and I can't seem to make this happen.

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by rgwan** [comment]
It seems that I have set GC_RATIO too high (12) and I have fulfill the Flash memory. And continually write to a sector causes that error

**Comment by dlbeer** [comment]
On Mon, May 16, 2016 at 05:58:12AM -0700, ZhiYuan Wan wrote:
> It seems that I have set GC_RATIO too high (12) and I have fulfill the
> Flash memory. And continually write to a sector causes that error

I've just tried modifying the map.c test program to rewrite one sector
1000 times before the main write test, and have set the GC_RATIO to 12.
I still can't make this happen.

I might have missed something, but if you're still quite sure that this
is a problem, could you please email me a test program
(dlbeer@gmail.com)?

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by rgwan** [comment]
I have sent test program to you. the flash simulator is pretty simple at here https://github.com/rgwan/embedFTL/blob/master/test/flash_sim.c (I have reserved serval blocks for system/boot/bbt)
and I saw pretty interesting thing. If I rewritten 0 block 40000 times. The journal said it has 40000 records, but once I restart it, it reports that the journal has 245505 records.

**Comment by rgwan** [comment]
But if I fill some other pages. Continally rewritten a page seems okay and it doesn't causes error.

**Comment by dlbeer** [comment]
On Mon, May 16, 2016 at 10:36:51PM -0700, ZhiYuan Wan wrote:
> I have sent test program to you. the flash simulator is pretty simple at here https://github.com/rgwan/embedFTL/blob/master/test/flash_sim.c (I have reserved serval blocks for system/boot/bbt)
> and I saw pretty interesting thing. If I rewritten 0 block 40000 times. The journal said it has 40000 records, but once I restart it, it reports that the journal has 245505 records.

I tried your test program with the flash simulator included in the dhara
source, and I get no errors.

Is it possible that you have a bug in your flash simulator?

Cheers,
Daniel

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by rgwan** [comment]
I m sure that my simulator hasnt bug....because I have check the data file....

**Comment by dlbeer** [comment]
Sorry, but I think a bug in your simulator is the most likely explanation for what you're seeing. The automated test suite specifically tests journal recovery, sector overwrite and garbage collection. If the bugs you're describing did exist, I would not expect those tests to pass.

I can't reproduce any of the behaviour you're seeing. Your test program does not reproduce the behaviour. A buggy underlying flash interface is an entirely plausible explanation for the problems you're describing, and it explains why the bugs disappear when your flash layer is not used.
