### ISSUE TITLE
Question on ECC depth/etc

### ISSUE THREAD

**Issue by duaneellissd** [dlbeer/dhara#14]
Sorry - this is not really an issue, it is more of a documentation question/issue.

The BCH implementation, how many correctable bits does it support?

ie: Typically some NAND solutions require 8bits of correction.

That answer is not clear to me 

Thanks.

**Comment by dlbeer** [comment]
On Tue, Nov 17, 2020 at 04:26:47PM -0800, duaneellissd wrote:
> Sorry - this is not really an issue, it is more of a documentation question/issue.
> 
> The BCH implementation, how many correctable bits does it support?
> 
> ie: Typically some NAND solutions require 8bits of correction.
> 
> That answer is not clear to me 
> 
> Thanks.

There are definitions in bch.h for 1, 2, 3 and 4-bits of correction.

Is the requirement that you've come across for 8 bits over a single ECC
chunk or over a multi-chunk page?

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by duaneellissd** [comment]
An example is the MT29F32, 64, 128, G08. Page 114 - table 16, 

Minimum number of valid blocks (NVB) per LUN 4016
Total available blocks per LUN 4096
First spare area location Byte 8192
Bad-block mark 00h
Minimum required ECC 8-bit ECC per 540 bytes of data

https://www.digikey.com/en/products/detail/micron-technology-inc/MT29F128G08CFABBWP-12IT-B-TR/6135552?s=N4IgTCBcDaIKxwOwFoCMAOAzJtyByAIgATIgC6AvkA

Chip size details:
Organization
– Page size x8: 8640 bytes (8192 + 448 bytes)
– Block size: 128 pages (1024K + 56K bytes)
– Plane size: 2 planes x 2048 blocks per plane
– Device size: 32Gb: 4096 blocks;
64Gb: 8192 blocks;
128Gb: 16,384 blocks;
256Gb: 32,768 blocks

**Comment by dlbeer** [comment]
On Wed, Nov 18, 2020 at 03:37:06PM -0800, duaneellissd wrote:
> An example is the MT29F32, 64, 128, G08. Page 114 - table 16, 
> 
> Minimum number of valid blocks (NVB) per LUN 4016
> Total available blocks per LUN 4096
> First spare area location Byte 8192
> Bad-block mark 00h
> Minimum required ECC 8-bit ECC per 540 bytes of data
> 
> https://www.digikey.com/en/products/detail/micron-technology-inc/MT29F128G08CFABBWP-12IT-B-TR/6135552?s=N4IgTCBcDaIKxwOwFoCMAOAzJtyByAIgATIgC6AvkA
> 
> Chip size details:
> Organization
> – Page size x8: 8640 bytes (8192 + 448 bytes)
> – Block size: 128 pages (1024K + 56K bytes)
> – Plane size: 2 planes x 2048 blocks per plane
> – Device size: 32Gb: 4096 blocks;
> 64Gb: 8192 blocks;
> 128Gb: 16,384 blocks;
> 256Gb: 32,768 blocks

Ok. The BCH code as it currently stands is probably unsuitable for that,
as it uses 64-bit integers to represent polynomials in GF(2), and an
8-bit polynominal will be of degree much larger than 63. It'd be
possible to change it, but I have no immediate plans to do so.

There are likely other ECC libraries available anyway (and some chips
have hardware support) -- there's no reason why you must use the
included implementation for that.

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by duaneellissd** [comment]
Q: How do I come up with the DEF values.

I'm looking at extending this to support 8bit correction over the 512 byte field.

Stated differently, what's an easy way to generate arbitrary polynomials of other sizes.

**Comment by dlbeer** [comment]
On Sat, Nov 21, 2020 at 11:50:21AM -0800, duaneellissd wrote:
> Q: How do I come up with the DEF values.
> 
> I'm looking at extending this to support 8bit correction over the 512 byte field.
> 
> Stated differently, what's an easy way to generate arbitrary polynomials of other sizes.

The polynomial for an N-bit BCH code is the product of polynomials whose
roots are the first 2N elements of the underlying field (GF(2^13) in
this case).

There is a tool included that you can use to find these polynomials, but
it will require modification also to support larger polynomials. This
command, for example, produces the parameters for the 4-bit ECC:

    ./tools/gftool 201b bch 8

Cheers,
Daniel

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by duaneellissd** [comment]
Cool that was helpful, I'm working on making this handle bigger items.
Questions:

A) what command would be used for the other forms (ie: 2bit, 4bit, etc) that exist already - 
My goal is to cross check & verify.

B) Going up to 8bit when/why would you use some starting polynomial other then 0x201b, 
for example the Linux implementation has 11 different polynomials

The only answer I can think of is if(POLY_A) creates a generator with a lower number of bits set. or lower degree, then at runtime some math operations would faster.

**Comment by dlbeer** [comment]
On Tue, Nov 24, 2020 at 02:33:02PM -0800, duaneellissd wrote:
> Cool that was helpful, I'm working on making this handle bigger items.
> Questions:
> 
> A) what command would be used for the other forms (ie: 2bit, 4bit, etc) that exist already - 
> My goal is to cross check & verify.

    ./gftool 201b bch 2
    ./gftool 201b bch 4
    ./gftool 201b bch 6
    ./gftool 201b bch 8

The number of roots is always twice the number of correctable errors.

> B) Going up to 8bit when/why would you use some starting polynomial other then 0x201b, 
> for example the Linux implementation has 11 different polynomials
> 
> The only answer I can think of is if(POLY_A) creates a generator with a lower number of bits set. or lower degree, then at runtime some math operations would faster.

I don't know of any good reason for software to use different values
(provided that the polynomial is irreducible). Some values may be better
or worse for hardware implementations, however.

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B
