### ISSUE TITLE
binary license attribution?

### ISSUE THREAD

**Issue by adamfk-jca** [dlbeer/dhara#15]
Hello,

very cool project. If I was to use this in a microcontroller without a user interface, how should I attribute the project? Do you require attribution for binary releases?

Thanks again!

**Comment by dlbeer** [comment]
On Thu, Nov 19, 2020 at 09:04:49AM -0800, adamfk-jca wrote:
> very cool project. If I was to use this in a microcontroller without a
> user interface, how should I attribute the project? Do you require
> attribution for binary releases?

It's not required, but it would be appreciated! If you have any
accompanying material or a website, somethere there would work perhaps.

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B
