### ISSUE TITLE
Can dhara be detected by linux as a device file?

### ISSUE THREAD

**Issue by kristianharge** [dlbeer/dhara#18]
Hello,

I am working with a micron MT29FABABA flash and I would like to add files directly to it. In order to do this I wanted to mount the device somewhere and just copy the files to it (as with an USB key), but before, I should recognize it as a device file (I am in linux so make it visible in the /dev directory).

Is it possible to do this with dhara?

If not, is there any known way to make dhara visible to a file system and add files to the flash directly?

**Comment by dlbeer** [comment]
On Tue, Feb 16, 2021 at 07:37:26AM -0800, Kristian wrote:
> Hello,
> 
> I am working with a micron MT29FABABA flash and I would like to add files directly to it. In order to do this I wanted to mount the device somewhere and just copy the files to it (as with an USB key), but before, I should recognize it as a device file (I am in linux so make it visible in the /dev directory).
> 
> Is it possible to do this with dhara?
> 
> If not, is there any known way to make dhara visible to a file system and add files to the flash directly?

Dhara itself doesn't do this -- you would need to implement a USB mass
storage device. You can handle the block read/write requests by passing
them to dhara though.

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B
