### ISSUE TITLE
When the bad block appears in the read ECC error, dhara cannot be processed

### ISSUE THREAD

**Issue by zbqxyz** [dlbeer/dhara#24]
@dlbeer 

when bad block appears in the read ecc error ,dhara cannot handle.But this is where many nand flash bad blocks appear to be characterized

**Comment by dlbeer** [comment]
Unfortunately there's no way to guarantee that any data can be recovered if arbitrary blocks can go bad long after they're written. If reading is your only means of detecting bad blocks, but you think they go bad during writing, then I'd recommend that you attempt a read-back of data immediately after programming in your NAND driver.

**Comment by zbqxyz** [comment]
> 
> 
> Unfortunately there's no way to guarantee that any data can be recovered if arbitrary blocks can go bad long after they're written. If reading is your only means of detecting bad blocks, but you think they go bad during writing, then I'd recommend that you attempt a read-back of data immediately after programming in your NAND driver.

There is a read-back comparison after writing inside the driver, but I test a situation where reading back the data immediately after writing is correct.  When reading again after some time, there will be ECC error.This block is this situation after I did 600,000 erases again

**Comment by dlbeer** [comment]
Do you mean 600,000 erases of the same block? That's likely far in excess of the manufacturer's specified limit, and at that point you probably couldn't expect it to work any more. If you use Dhara on a chip from the start, it will wear-level your writes and remain under the manufacturer's limit for as long as possible on each block.

**Comment by int32cn** [comment]
你好，
你的邮件已收到，谢谢！！
此为自动回复。
