### ISSUE TITLE
Using a different GC ratio with an existing flash map

### ISSUE THREAD

**Issue by PTaylor-us** [dlbeer/dhara#27]
Thank you for the incredible library. It takes so many of the pain points out of using flash memory in embedded systems. 

I'm finding myself in a position where I need a bit more control over GC. I've previously been using a GC ratio of `1`, but may need to switch to manual GC. The dhara_map_init documentation states "You should always initialize the same chip with the same garbage collection ratio". Is there some wiggle room around that "should". It doesn't say "must", so I interpret that it "could" be done. If that is the case, what are the possible ramifications of init'ing a chip (previously init'ed with GC ratio = `1`) with a GC ratio = `0` and using `dhara_map_gc` for manual collection?

**Comment by dlbeer** [comment]
Glad to hear it's useful!

**Comment by PTaylor-us** [comment]
Excellent, that's exactly what I needed to know. Thank you!
