### ISSUE TITLE
Garbage Collection Instrumentation

### ISSUE THREAD

**Issue by PTaylor-us** [dlbeer/dhara#28]
When using manual GC (using a gc ratio of 0 and calling `dhara_map_gc()`), is there any way to determine whether/how-much garbage exists? If not, is there a relatively simple way to add that functionality?

related to #27

**Comment by dlbeer** [comment]
On Wed, Sep 29, 2021 at 10:40:09AM -0700, Peter Taylor wrote:
> When using manual GC (using a gc ratio of 0 and calling
> `dhara_map_gc()`), is there any way to determine whether/how-much
> garbage exists? If not, is there a relatively simple way to add that
> functionality?

Unfortunately not. You can rely on it not being a greater portion of
usage pages than 1/(GC_RATIO+1) of the flash, if that's any use.

-- 
Daniel Beer ***@***.***> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by PTaylor-us** [comment]
Thanks for the quick response. I'll probably do a combination of periodic and as-needed.
