### ISSUE TITLE
Example Programs for each feature

### ISSUE THREAD

**Issue by hchaudhary1** [dlbeer/dhara#3]
This is a great code.
I don't see too much documentation of the API. Is there an example code for each feature that is available so that one can learn the API?

I do see the many test codes (perhaps these are the example codes?), but I am not sure the purpose of each of those, and where and when they apply.

Thanks

**Comment by dlbeer** [comment]
On Tue, Dec 05, 2017 at 09:54:53PM +0000, hchaudhary1 wrote:
> This is a great code.
> I don't see too much documentation of the API. Is there an example code for each feature that is available so that one can learn the API?
> 
> I do see the many test codes (perhaps these are the example codes?), but I am not sure the purpose of each of those, and where and when they apply.

There is a list of calls in the README and some explanatory comments in
dhara/map.h, but that's about it.

There isn't much to the API: just call init() and resume() on startup,
and then use read()/write()/sync() as you would for a normal
write-buffered block device.

Cheers,
Daniel

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by hchaudhary1** [comment]
When you say it that way, I suppose you are right.. its quite easy! Thanks
