### ISSUE TITLE
DHARA_E_MAP_FULL occurs

### ISSUE THREAD

**Issue by biovoid** [dlbeer/dhara#4]
After using dhara_map_write() as layer for FatFs the m->count become full. It can be decremented only with dhara_map_trim(). How should it used?

**Comment by dlbeer** [comment]
On Thu, Jun 07, 2018 at 06:26:42PM +0000, biovoid wrote:
> After using dhara_map_write() as layer for FatFs the m->count become
> full. It can be decremented only with dhara_map_trim(). How should it
> used?   

It will only become full if you try to store more distinct sectors than
the map has capacity for. Overwriting old sectors (as would happen in a
normal block device) does not increase the count of live sectors. Under
normal block-device-like circumstances, trim() is an optional operation.

Cheers,
Daniel

-- 
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by biovoid** [comment]
The problem was in my incorrect implementation of the method dhara_nand_is_free().
