### ISSUE TITLE
dhara_journal_resume issue

### ISSUE THREAD

**Issue by gtsee** [dlbeer/dhara#5]
I'm having an infrequent issue in `dhara_journal_resume` that occurs after power failure when epoch is 0xFF. During journal resume, `find_root` finds an empty page (all bytes are 0xFF so the epoch matches) which results in the journal being populated with invalid data.

It looks like `find_root` needs a check to make sure that it found a valid checkpoint to base the root on. I'm currently testing the following fix and it appears to have resolved the issue.

```diff
static int find_root(struct dhara_journal *j, dhara_page_t start,
		     dhara_error_t *err)
{
	const dhara_block_t blk = start >> j->nand->log2_ppb;
	int i = (start & ((1 << j->nand->log2_ppb) - 1)) >> j->log2_ppc;

	while (i >= 0) {
		const dhara_page_t p = (blk << j->nand->log2_ppb) +
			((i + 1) << j->log2_ppc) - 1;

		if (!dhara_nand_read(j->nand, p,
				     0, 1 << j->nand->log2_page_size,
						 j->page_buf, err) &&
+                   (hdr_has_magic(j->page_buf)) &&
		    (hdr_get_epoch(j->page_buf) == j->epoch)) {
			j->root = p - 1;
			return 0;
		}

		i--;
	}

	dhara_set_error(err, DHARA_E_TOO_BAD);
	return -1;
}
```

**Comment by dlbeer** [comment]
Yep, you're right. I've just committed your suggest fix for this now.
